package com.yaabelozerov.moodb.presentation.theme.colors
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

private val primaryLight = Color(0xFF984800)
private val onPrimaryLight = Color(0xFFFFFFFF)
private val primaryContainerLight = Color(0xFFFF8931)
private val onPrimaryContainerLight = Color(0xFF652E00)
private val secondaryLight = Color(0xFF86522F)
private val onSecondaryLight = Color(0xFFFFFFFF)
private val secondaryContainerLight = Color(0xFFFFBA90)
private val onSecondaryContainerLight = Color(0xFF7A4826)
private val tertiaryLight = Color(0xFF5D6300)
private val onTertiaryLight = Color(0xFFFFFFFF)
private val tertiaryContainerLight = Color(0xFFA6B00B)
private val onTertiaryContainerLight = Color(0xFF3C4000)
private val errorLight = Color(0xFFBA1A1A)
private val onErrorLight = Color(0xFFFFFFFF)
private val errorContainerLight = Color(0xFFFFDAD6)
private val onErrorContainerLight = Color(0xFF93000A)
private val backgroundLight = Color(0xFFFFF8F5)
private val onBackgroundLight = Color(0xFF241913)
private val surfaceLight = Color(0xFFFFF8F5)
private val onSurfaceLight = Color(0xFF241913)
private val surfaceVariantLight = Color(0xFFFBDDCC)
private val onSurfaceVariantLight = Color(0xFF564337)
private val outlineLight = Color(0xFF8A7265)
private val outlineVariantLight = Color(0xFFDDC1B1)
private val scrimLight = Color(0xFF000000)
private val inverseSurfaceLight = Color(0xFF3A2E27)
private val inverseOnSurfaceLight = Color(0xFFFFEDE5)
private val inversePrimaryLight = Color(0xFFFFB689)
private val surfaceDimLight = Color(0xFFEAD6CC)
private val surfaceBrightLight = Color(0xFFFFF8F5)
private val surfaceContainerLowestLight = Color(0xFFFFFFFF)
private val surfaceContainerLowLight = Color(0xFFFFF1EA)
private val surfaceContainerLight = Color(0xFFFFEADF)
private val surfaceContainerHighLight = Color(0xFFF9E4D9)
private val surfaceContainerHighestLight = Color(0xFFF3DED4)

private val primaryDark = Color(0xFFFFB689)
private val onPrimaryDark = Color(0xFF512300)
private val primaryContainerDark = Color(0xFFFF8931)
private val onPrimaryContainerDark = Color(0xFF652E00)
private val secondaryDark = Color(0xFFFCB78D)
private val onSecondaryDark = Color(0xFF4F2506)
private val secondaryContainerDark = Color(0xFF6A3B1A)
private val onSecondaryContainerDark = Color(0xFFE9A67D)
private val tertiaryDark = Color(0xFFC4CF34)
private val onTertiaryDark = Color(0xFF303300)
private val tertiaryContainerDark = Color(0xFFA6B00B)
private val onTertiaryContainerDark = Color(0xFF3C4000)
private val errorDark = Color(0xFFFFB4AB)
private val onErrorDark = Color(0xFF690005)
private val errorContainerDark = Color(0xFF93000A)
private val onErrorContainerDark = Color(0xFFFFDAD6)
private val backgroundDark = Color(0xFF1B110B)
private val onBackgroundDark = Color(0xFFF3DED4)
private val surfaceDark = Color(0xFF1B110B)
private val onSurfaceDark = Color(0xFFF3DED4)
private val surfaceVariantDark = Color(0xFF564337)
private val onSurfaceVariantDark = Color(0xFFDDC1B1)
private val outlineDark = Color(0xFFA58C7D)
private val outlineVariantDark = Color(0xFF564337)
private val scrimDark = Color(0xFF000000)
private val inverseSurfaceDark = Color(0xFFF3DED4)
private val inverseOnSurfaceDark = Color(0xFF3A2E27)
private val inversePrimaryDark = Color(0xFF984800)
private val surfaceDimDark = Color(0xFF1B110B)
private val surfaceBrightDark = Color(0xFF43372F)
private val surfaceContainerLowestDark = Color(0xFF150C07)
private val surfaceContainerLowDark = Color(0xFF241913)
private val surfaceContainerDark = Color(0xFF281D17)
private val surfaceContainerHighDark = Color(0xFF332821)
private val surfaceContainerHighestDark = Color(0xFF3F322B)

val LightColorScheme = lightColorScheme(
    primary = primaryLight,
    onPrimary = onPrimaryLight,
    primaryContainer = primaryContainerLight,
    onPrimaryContainer = onPrimaryContainerLight,
    secondary = secondaryLight,
    onSecondary = onSecondaryLight,
    secondaryContainer = secondaryContainerLight,
    onSecondaryContainer = onSecondaryContainerLight,
    tertiary = tertiaryLight,
    onTertiary = onTertiaryLight,
    tertiaryContainer = tertiaryContainerLight,
    onTertiaryContainer = onTertiaryContainerLight,
    error = errorLight,
    onError = onErrorLight,
    errorContainer = errorContainerLight,
    onErrorContainer = onErrorContainerLight,
    background = backgroundLight,
    onBackground = onBackgroundLight,
    surface = surfaceLight,
    onSurface = onSurfaceLight,
    surfaceVariant = surfaceVariantLight,
    onSurfaceVariant = onSurfaceVariantLight,
    outline = outlineLight,
    outlineVariant = outlineVariantLight,
    scrim = scrimLight,
    inverseSurface = inverseSurfaceLight,
    inverseOnSurface = inverseOnSurfaceLight,
    inversePrimary = inversePrimaryLight,
    surfaceDim = surfaceDimLight,
    surfaceBright = surfaceBrightLight,
    surfaceContainerLowest = surfaceContainerLowestLight,
    surfaceContainerLow = surfaceContainerLowLight,
    surfaceContainer = surfaceContainerLight,
    surfaceContainerHigh = surfaceContainerHighLight,
    surfaceContainerHighest = surfaceContainerHighestLight,
)

val DarkColorScheme = darkColorScheme(
    primary = primaryDark,
    onPrimary = onPrimaryDark,
    primaryContainer = primaryContainerDark,
    onPrimaryContainer = onPrimaryContainerDark,
    secondary = secondaryDark,
    onSecondary = onSecondaryDark,
    secondaryContainer = secondaryContainerDark,
    onSecondaryContainer = onSecondaryContainerDark,
    tertiary = tertiaryDark,
    onTertiary = onTertiaryDark,
    tertiaryContainer = tertiaryContainerDark,
    onTertiaryContainer = onTertiaryContainerDark,
    error = errorDark,
    onError = onErrorDark,
    errorContainer = errorContainerDark,
    onErrorContainer = onErrorContainerDark,
    background = backgroundDark,
    onBackground = onBackgroundDark,
    surface = surfaceDark,
    onSurface = onSurfaceDark,
    surfaceVariant = surfaceVariantDark,
    onSurfaceVariant = onSurfaceVariantDark,
    outline = outlineDark,
    outlineVariant = outlineVariantDark,
    scrim = scrimDark,
    inverseSurface = inverseSurfaceDark,
    inverseOnSurface = inverseOnSurfaceDark,
    inversePrimary = inversePrimaryDark,
    surfaceDim = surfaceDimDark,
    surfaceBright = surfaceBrightDark,
    surfaceContainerLowest = surfaceContainerLowestDark,
    surfaceContainerLow = surfaceContainerLowDark,
    surfaceContainer = surfaceContainerDark,
    surfaceContainerHigh = surfaceContainerHighDark,
    surfaceContainerHighest = surfaceContainerHighestDark,
)

