package com.yaabelozerov.moodb.presentation.theme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

private val primaryLight = Color(0xFF984800)
private val onPrimaryLight = Color(0xFFFFFFFF)
private val primaryContainerLight = Color(0xFFFF8931)
private val onPrimaryContainerLight = Color(0xFF652E00)
private val secondaryLight = Color(0xFF86522F)
private val onSecondaryLight = Color(0xFFFFFFFF)
private val secondaryContainerLight = Color(0xFFFFBA90)
private val onSecondaryContainerLight = Color(0xFF7A4826)
private val tertiaryLight = Color(0xFF5D6300)
private val onTertiaryLight = Color(0xFFFFFFFF)
private val tertiaryContainerLight = Color(0xFFA6B00B)
private val onTertiaryContainerLight = Color(0xFF3C4000)
private val errorLight = Color(0xFFBA1A1A)
private val onErrorLight = Color(0xFFFFFFFF)
private val errorContainerLight = Color(0xFFFFDAD6)
private val onErrorContainerLight = Color(0xFF93000A)
private val backgroundLight = Color(0xFFFFF8F5)
private val onBackgroundLight = Color(0xFF241913)
private val surfaceLight = Color(0xFFFFF8F5)
private val onSurfaceLight = Color(0xFF241913)
private val surfaceVariantLight = Color(0xFFFBDDCC)
private val onSurfaceVariantLight = Color(0xFF564337)
private val outlineLight = Color(0xFF8A7265)
private val outlineVariantLight = Color(0xFFDDC1B1)
private val scrimLight = Color(0xFF000000)
private val inverseSurfaceLight = Color(0xFF3A2E27)
private val inverseOnSurfaceLight = Color(0xFFFFEDE5)
private val inversePrimaryLight = Color(0xFFFFB689)
private val surfaceDimLight = Color(0xFFEAD6CC)
private val surfaceBrightLight = Color(0xFFFFF8F5)
private val surfaceContainerLowestLight = Color(0xFFFFFFFF)
private val surfaceContainerLowLight = Color(0xFFFFF1EA)
private val surfaceContainerLight = Color(0xFFFFEADF)
private val surfaceContainerHighLight = Color(0xFFF9E4D9)
private val surfaceContainerHighestLight = Color(0xFFF3DED4)

private val primaryLightMediumContrast = Color(0xFF5A2800)
private val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
private val primaryContainerLightMediumContrast = Color(0xFFAE5300)
private val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
private val secondaryLightMediumContrast = Color(0xFF562B0B)
private val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
private val secondaryContainerLightMediumContrast = Color(0xFF97603C)
private val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
private val tertiaryLightMediumContrast = Color(0xFF353900)
private val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
private val tertiaryContainerLightMediumContrast = Color(0xFF6B7200)
private val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
private val errorLightMediumContrast = Color(0xFF740006)
private val onErrorLightMediumContrast = Color(0xFFFFFFFF)
private val errorContainerLightMediumContrast = Color(0xFFCF2C27)
private val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
private val backgroundLightMediumContrast = Color(0xFFFFF8F5)
private val onBackgroundLightMediumContrast = Color(0xFF241913)
private val surfaceLightMediumContrast = Color(0xFFFFF8F5)
private val onSurfaceLightMediumContrast = Color(0xFF190F09)
private val surfaceVariantLightMediumContrast = Color(0xFFFBDDCC)
private val onSurfaceVariantLightMediumContrast = Color(0xFF453227)
private val outlineLightMediumContrast = Color(0xFF634E42)
private val outlineVariantLightMediumContrast = Color(0xFF7F685B)
private val scrimLightMediumContrast = Color(0xFF000000)
private val inverseSurfaceLightMediumContrast = Color(0xFF3A2E27)
private val inverseOnSurfaceLightMediumContrast = Color(0xFFFFEDE5)
private val inversePrimaryLightMediumContrast = Color(0xFFFFB689)
private val surfaceDimLightMediumContrast = Color(0xFFD6C3B9)
private val surfaceBrightLightMediumContrast = Color(0xFFFFF8F5)
private val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
private val surfaceContainerLowLightMediumContrast = Color(0xFFFFF1EA)
private val surfaceContainerLightMediumContrast = Color(0xFFF9E4D9)
private val surfaceContainerHighLightMediumContrast = Color(0xFFEDD9CE)
private val surfaceContainerHighestLightMediumContrast = Color(0xFFE2CEC3)

private val primaryLightHighContrast = Color(0xFF4B2000)
private val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
private val primaryContainerLightHighContrast = Color(0xFF773700)
private val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
private val secondaryLightHighContrast = Color(0xFF492103)
private val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
private val secondaryContainerLightHighContrast = Color(0xFF6D3D1C)
private val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
private val tertiaryLightHighContrast = Color(0xFF2B2F00)
private val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
private val tertiaryContainerLightHighContrast = Color(0xFF484D00)
private val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
private val errorLightHighContrast = Color(0xFF600004)
private val onErrorLightHighContrast = Color(0xFFFFFFFF)
private val errorContainerLightHighContrast = Color(0xFF98000A)
private val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
private val backgroundLightHighContrast = Color(0xFFFFF8F5)
private val onBackgroundLightHighContrast = Color(0xFF241913)
private val surfaceLightHighContrast = Color(0xFFFFF8F5)
private val onSurfaceLightHighContrast = Color(0xFF000000)
private val surfaceVariantLightHighContrast = Color(0xFFFBDDCC)
private val onSurfaceVariantLightHighContrast = Color(0xFF000000)
private val outlineLightHighContrast = Color(0xFF3A281E)
private val outlineVariantLightHighContrast = Color(0xFF594539)
private val scrimLightHighContrast = Color(0xFF000000)
private val inverseSurfaceLightHighContrast = Color(0xFF3A2E27)
private val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
private val inversePrimaryLightHighContrast = Color(0xFFFFB689)
private val surfaceDimLightHighContrast = Color(0xFFC8B5AB)
private val surfaceBrightLightHighContrast = Color(0xFFFFF8F5)
private val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
private val surfaceContainerLowLightHighContrast = Color(0xFFFFEDE5)
private val surfaceContainerLightHighContrast = Color(0xFFF3DED4)
private val surfaceContainerHighLightHighContrast = Color(0xFFE5D0C6)
private val surfaceContainerHighestLightHighContrast = Color(0xFFD6C3B9)

private val primaryDark = Color(0xFFFFB689)
private val onPrimaryDark = Color(0xFF512300)
private val primaryContainerDark = Color(0xFFFF8931)
private val onPrimaryContainerDark = Color(0xFF652E00)
private val secondaryDark = Color(0xFFFCB78D)
private val onSecondaryDark = Color(0xFF4F2506)
private val secondaryContainerDark = Color(0xFF6A3B1A)
private val onSecondaryContainerDark = Color(0xFFE9A67D)
private val tertiaryDark = Color(0xFFC4CF34)
private val onTertiaryDark = Color(0xFF303300)
private val tertiaryContainerDark = Color(0xFFA6B00B)
private val onTertiaryContainerDark = Color(0xFF3C4000)
private val errorDark = Color(0xFFFFB4AB)
private val onErrorDark = Color(0xFF690005)
private val errorContainerDark = Color(0xFF93000A)
private val onErrorContainerDark = Color(0xFFFFDAD6)
private val backgroundDark = Color(0xFF1B110B)
private val onBackgroundDark = Color(0xFFF3DED4)
private val surfaceDark = Color(0xFF1B110B)
private val onSurfaceDark = Color(0xFFF3DED4)
private val surfaceVariantDark = Color(0xFF564337)
private val onSurfaceVariantDark = Color(0xFFDDC1B1)
private val outlineDark = Color(0xFFA58C7D)
private val outlineVariantDark = Color(0xFF564337)
private val scrimDark = Color(0xFF000000)
private val inverseSurfaceDark = Color(0xFFF3DED4)
private val inverseOnSurfaceDark = Color(0xFF3A2E27)
private val inversePrimaryDark = Color(0xFF984800)
private val surfaceDimDark = Color(0xFF1B110B)
private val surfaceBrightDark = Color(0xFF43372F)
private val surfaceContainerLowestDark = Color(0xFF150C07)
private val surfaceContainerLowDark = Color(0xFF241913)
private val surfaceContainerDark = Color(0xFF281D17)
private val surfaceContainerHighDark = Color(0xFF332821)
private val surfaceContainerHighestDark = Color(0xFF3F322B)

private val primaryDarkMediumContrast = Color(0xFFFFD4BB)
private val onPrimaryDarkMediumContrast = Color(0xFF411B00)
private val primaryContainerDarkMediumContrast = Color(0xFFFF8931)
private val onPrimaryContainerDarkMediumContrast = Color(0xFF351500)
private val secondaryDarkMediumContrast = Color(0xFFFFD4BB)
private val onSecondaryDarkMediumContrast = Color(0xFF411B00)
private val secondaryContainerDarkMediumContrast = Color(0xFFC0835C)
private val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
private val tertiaryDarkMediumContrast = Color(0xFFDAE549)
private val onTertiaryDarkMediumContrast = Color(0xFF252800)
private val tertiaryContainerDarkMediumContrast = Color(0xFFA6B00B)
private val onTertiaryContainerDarkMediumContrast = Color(0xFF1D1F00)
private val errorDarkMediumContrast = Color(0xFFFFD2CC)
private val onErrorDarkMediumContrast = Color(0xFF540003)
private val errorContainerDarkMediumContrast = Color(0xFFFF5449)
private val onErrorContainerDarkMediumContrast = Color(0xFF000000)
private val backgroundDarkMediumContrast = Color(0xFF1B110B)
private val onBackgroundDarkMediumContrast = Color(0xFFF3DED4)
private val surfaceDarkMediumContrast = Color(0xFF1B110B)
private val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
private val surfaceVariantDarkMediumContrast = Color(0xFF564337)
private val onSurfaceVariantDarkMediumContrast = Color(0xFFF4D6C6)
private val outlineDarkMediumContrast = Color(0xFFC8AC9D)
private val outlineVariantDarkMediumContrast = Color(0xFFA48B7D)
private val scrimDarkMediumContrast = Color(0xFF000000)
private val inverseSurfaceDarkMediumContrast = Color(0xFFF3DED4)
private val inverseOnSurfaceDarkMediumContrast = Color(0xFF332821)
private val inversePrimaryDarkMediumContrast = Color(0xFF753600)
private val surfaceDimDarkMediumContrast = Color(0xFF1B110B)
private val surfaceBrightDarkMediumContrast = Color(0xFF4F423A)
private val surfaceContainerLowestDarkMediumContrast = Color(0xFF0E0603)
private val surfaceContainerLowDarkMediumContrast = Color(0xFF261B15)
private val surfaceContainerDarkMediumContrast = Color(0xFF31251F)
private val surfaceContainerHighDarkMediumContrast = Color(0xFF3C3029)
private val surfaceContainerHighestDarkMediumContrast = Color(0xFF483B34)

private val primaryDarkHighContrast = Color(0xFFFFECE3)
private val onPrimaryDarkHighContrast = Color(0xFF000000)
private val primaryContainerDarkHighContrast = Color(0xFFFFB180)
private val onPrimaryContainerDarkHighContrast = Color(0xFF190600)
private val secondaryDarkHighContrast = Color(0xFFFFECE3)
private val onSecondaryDarkHighContrast = Color(0xFF000000)
private val secondaryContainerDarkHighContrast = Color(0xFFF8B489)
private val onSecondaryContainerDarkHighContrast = Color(0xFF190600)
private val tertiaryDarkHighContrast = Color(0xFFEEF95C)
private val onTertiaryDarkHighContrast = Color(0xFF000000)
private val tertiaryContainerDarkHighContrast = Color(0xFFC1CB30)
private val onTertiaryContainerDarkHighContrast = Color(0xFF0B0C00)
private val errorDarkHighContrast = Color(0xFFFFECE9)
private val onErrorDarkHighContrast = Color(0xFF000000)
private val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
private val onErrorContainerDarkHighContrast = Color(0xFF220001)
private val backgroundDarkHighContrast = Color(0xFF1B110B)
private val onBackgroundDarkHighContrast = Color(0xFFF3DED4)
private val surfaceDarkHighContrast = Color(0xFF1B110B)
private val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
private val surfaceVariantDarkHighContrast = Color(0xFF564337)
private val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
private val outlineDarkHighContrast = Color(0xFFFFECE3)
private val outlineVariantDarkHighContrast = Color(0xFFD9BDAD)
private val scrimDarkHighContrast = Color(0xFF000000)
private val inverseSurfaceDarkHighContrast = Color(0xFFF3DED4)
private val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
private val inversePrimaryDarkHighContrast = Color(0xFF753600)
private val surfaceDimDarkHighContrast = Color(0xFF1B110B)
private val surfaceBrightDarkHighContrast = Color(0xFF5B4D45)
private val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
private val surfaceContainerLowDarkHighContrast = Color(0xFF281D17)
private val surfaceContainerDarkHighContrast = Color(0xFF3A2E27)
private val surfaceContainerHighDarkHighContrast = Color(0xFF463932)
private val surfaceContainerHighestDarkHighContrast = Color(0xFF51443C)

val LightColorScheme = lightColorScheme(
    primary = primaryLight,
    onPrimary = onPrimaryLight,
    primaryContainer = primaryContainerLight,
    onPrimaryContainer = onPrimaryContainerLight,
    secondary = secondaryLight,
    onSecondary = onSecondaryLight,
    secondaryContainer = secondaryContainerLight,
    onSecondaryContainer = onSecondaryContainerLight,
    tertiary = tertiaryLight,
    onTertiary = onTertiaryLight,
    tertiaryContainer = tertiaryContainerLight,
    onTertiaryContainer = onTertiaryContainerLight,
    error = errorLight,
    onError = onErrorLight,
    errorContainer = errorContainerLight,
    onErrorContainer = onErrorContainerLight,
    background = backgroundLight,
    onBackground = onBackgroundLight,
    surface = surfaceLight,
    onSurface = onSurfaceLight,
    surfaceVariant = surfaceVariantLight,
    onSurfaceVariant = onSurfaceVariantLight,
    outline = outlineLight,
    outlineVariant = outlineVariantLight,
    scrim = scrimLight,
    inverseSurface = inverseSurfaceLight,
    inverseOnSurface = inverseOnSurfaceLight,
    inversePrimary = inversePrimaryLight,
    surfaceDim = surfaceDimLight,
    surfaceBright = surfaceBrightLight,
    surfaceContainerLowest = surfaceContainerLowestLight,
    surfaceContainerLow = surfaceContainerLowLight,
    surfaceContainer = surfaceContainerLight,
    surfaceContainerHigh = surfaceContainerHighLight,
    surfaceContainerHighest = surfaceContainerHighestLight,
)

val DarkColorScheme = darkColorScheme(
    primary = primaryDark,
    onPrimary = onPrimaryDark,
    primaryContainer = primaryContainerDark,
    onPrimaryContainer = onPrimaryContainerDark,
    secondary = secondaryDark,
    onSecondary = onSecondaryDark,
    secondaryContainer = secondaryContainerDark,
    onSecondaryContainer = onSecondaryContainerDark,
    tertiary = tertiaryDark,
    onTertiary = onTertiaryDark,
    tertiaryContainer = tertiaryContainerDark,
    onTertiaryContainer = onTertiaryContainerDark,
    error = errorDark,
    onError = onErrorDark,
    errorContainer = errorContainerDark,
    onErrorContainer = onErrorContainerDark,
    background = backgroundDark,
    onBackground = onBackgroundDark,
    surface = surfaceDark,
    onSurface = onSurfaceDark,
    surfaceVariant = surfaceVariantDark,
    onSurfaceVariant = onSurfaceVariantDark,
    outline = outlineDark,
    outlineVariant = outlineVariantDark,
    scrim = scrimDark,
    inverseSurface = inverseSurfaceDark,
    inverseOnSurface = inverseOnSurfaceDark,
    inversePrimary = inversePrimaryDark,
    surfaceDim = surfaceDimDark,
    surfaceBright = surfaceBrightDark,
    surfaceContainerLowest = surfaceContainerLowestDark,
    surfaceContainerLow = surfaceContainerLowDark,
    surfaceContainer = surfaceContainerDark,
    surfaceContainerHigh = surfaceContainerHighDark,
    surfaceContainerHighest = surfaceContainerHighestDark,
)

